
(()=>{
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const pre=$('#preloader'); window.addEventListener('load',()=>setTimeout(()=>pre.classList.add('hide'),380));
const header=$('#header'), progress=$('#progress');
const onScroll=()=>{const y=scrollY; header.classList.toggle('scrolled',y>24); const h=document.documentElement.scrollHeight-innerHeight; progress.style.width=(h?y/h*100:0)+'%'}; addEventListener('scroll',onScroll,{passive:true}); onScroll();
const menu=$('#menu'), nav=$('#navlinks'); menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)}); $$('#navlinks a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12}); $$('.reveal').forEach(el=>io.observe(el));
const sections=$$('main section[id]'); const spy=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){$$('#navlinks a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-40% 0px -50% 0px'});sections.forEach(s=>spy.observe(s));
$$('.tab').forEach(t=>t.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const f=t.dataset.filter;$$('.service-card').forEach(c=>c.classList.toggle('hidden',f!=='all'&&c.dataset.cat!==f))}));
$$('.service-cta').forEach(a=>a.addEventListener('click',()=>{const s=a.dataset.service;if(s){$('#servico').value='Outro';$('#mensagem').value='Tenho interesse em: '+s+'. ';setTimeout(()=>$('#mensagem').focus(),450)}}));
$('#quoteForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);const text=`Olá! Conheci a TAJO Digital 3F pelo site e gostaria de solicitar um orçamento.\n\nNome: ${d.get('nome')||'-'}\nEmpresa: ${d.get('empresa')||'-'}\nWhatsApp: ${d.get('whatsapp')||'-'}\nServiço: ${d.get('servico')||'-'}\nMensagem: ${d.get('mensagem')||'-'}`;window.open('https://wa.me/5527999639610?text='+encodeURIComponent(text),'_blank','noopener')});
$$('.work').forEach(w=>{w.addEventListener('pointermove',e=>{const r=w.getBoundingClientRect();w.style.setProperty('--mx',((e.clientX-r.left)/r.width*100)+'%');w.style.setProperty('--my',((e.clientY-r.top)/r.height*100)+'%')});const b=$('.work-open',w);b.addEventListener('click',()=>{const m=$('#modal');$('#modalTitle').textContent=w.dataset.title;$('#modalCat').textContent=w.dataset.cat;m.classList.add('open');m.setAttribute('aria-hidden','false');$('#modalClose').focus()})});
const closeModal=()=>{$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')};$('#modalClose').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
if(matchMedia('(pointer:fine)').matches){const cur=$('#cursor');addEventListener('pointermove',e=>{cur.style.left=e.clientX+'px';cur.style.top=e.clientY+'px'});$$('.magnetic').forEach(b=>b.addEventListener('pointermove',e=>{const r=b.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;b.style.transform=`translate(${x*.08}px,${y*.08}px) translateY(-2px)`}).addEventListener('pointerleave',()=>b.style.transform=''))}
const stage=$('#logoStage'); if(stage&&matchMedia('(pointer:fine)').matches){stage.closest('.hero-art').addEventListener('pointermove',e=>{const r=stage.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/r.width,y=(e.clientY-r.top-r.height/2)/r.height;stage.style.transform=`perspective(900px) rotateY(${x*7}deg) rotateX(${-y*7}deg)`});stage.closest('.hero-art').addEventListener('pointerleave',()=>stage.style.transform='')}
})();
